SELECT
	JCZ.JCDXH 排口ID,
	JCZ.WRWBH 污染物ID,
	JCZ.JCSJ 监测时间,
	JCZ.JCZ 污染物浓度值,
	JCZ.XYWRWPFL 污染物排放量,
	JCJ.LLORPFLXYZ 排放量,
	JCJ.PJLLORPFLXYZ 流量,
	HYL.PJJCZ 含氧量
FROM
	( SELECT JCDXH, WRWBH, JCSJ, CASE WHEN XYZSZ IS NOT NULL THEN XYZSZ ELSE XYZ END AS JCZ, XYWRWPFL FROM T_ZXJC_JCSJ_FQ_RSJ_JCZ WHERE JCZ IS NOT NULL ) JCZ
	LEFT JOIN ( SELECT XTXH, JCSJ, LLORPFLXYZ, PJLLORPFLXYZ FROM T_ZXJC_JCSJ_FQ_RSJ_JCJ ) JCJ ON JCZ.JCDXH = JCJ.XTXH AND JCZ.JCSJ = JCJ.JCSJ
	LEFT JOIN ( SELECT JCDXH, JCSJ, PJJCZ FROM T_ZXJC_JCSJ_FQ_RSJ_ZSYZJCZ WHERE JCXMBH = 'a99411' ) HYL ON JCZ.JCDXH = HYL.JCDXH AND JCZ.JCSJ = HYL.JCSJ
	INNER JOIN ( SELECT DISTINCT XH, SHSJ FROM T_ZXJC_WRY_JCD WHERE JCDMC NOT LIKE '%进水%' AND JCDMC NOT LIKE '%雨水%' AND SHZT = 1 ) PKMC ON JCZ.JCDXH = PKMC.XH
	INNER JOIN ( SELECT DISTINCT JCDXH FROM T_ZXJC_WRY_JCDGLYZ ) VALIDPK ON JCZ.JCDXH = VALIDPK.JCDXH
WHERE
	JCZ.JCSJ BETWEEN to_date( SUBSTR( '{}', 1, 19 ), 'yyyy-MM-dd HH24:mi:ss' )
	AND to_date( SUBSTR( '{}', 1, 19 ), 'yyyy-MM-dd HH24:mi:ss' )
    AND JCZ.JCSJ > PKMC.SHSJ + NUMTODSINTERVAL(7, 'DAY')