SELECT DISTINCT
	XH,
	SHSJ 
FROM
	T_ZXJC_WRY_JCD JCD
	INNER JOIN ( SELECT DISTINCT JCDXH FROM T_ZXJC_WRY_JCDGLYZ ) VALIDPK ON JCD.XH = VALIDPK.JCDXH
WHERE
	JCDMC NOT LIKE '%进水%' 
	AND JCDMC NOT LIKE '%雨水%'
	AND SHZT = 1