SELECT DISTINCT
	JBXX.WRYMC 企业名称,
	JBXX.XH 企业ID,
	SHI.XZQH 城市名称,
	JBXX.SHI 城市ID,
	QX.XZQH 区县名称,
	JBXX.QX 区县ID,
	JCD.JCDMC 排口名称,
	JCD.XH 排口ID
FROM
	T_ZXJC_WRY_JBXX JBXX
	LEFT JOIN T_COMN_XZQHDM SHI ON JBXX.QX = SHI.XZQHDM
	LEFT JOIN T_COMN_XZQHDM QX ON JBXX.SHI = QX.XZQHDM
	LEFT JOIN (SELECT XTXH,JCDMC,XH,SHSJ FROM T_ZXJC_WRY_JCD) JCD ON JBXX.XH = JCD.XTXH
	INNER JOIN (SELECT DISTINCT JCDXH FROM T_ZXJC_WRY_JCDGLYZ) VALIDPK ON JCD.XH = VALIDPK.JCDXH
WHERE
	JBXX.WRYMC NOT LIKE '%测试%'
	AND JCD.XH IS NOT NULL
	AND JCD.JCDMC NOT LIKE '%进水%'
	AND JCD.JCDMC NOT LIKE '%雨水%'